AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Express SMS API for sending OTP messages
Globals:
  Function:
    Timeout: 10
    LoggingConfig:
      LogFormat: JSON

Resources:
  ExpressSmsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: /
      Handler: server.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          NODE_ENV: production
      Events:
        ExpressApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  ExpressApi:
    Description: API Gateway endpoint URL for Prod stage for Express function
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
  ExpressFunction:
    Description: Express Lambda Function ARN
    Value: !GetAtt ExpressSmsFunction.Arn
  ExpressFunctionIamRole:
    Description: Implicit IAM Role created for Express function
    Value: !GetAtt ExpressSmsFunctionRole.Arn
